#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

ln -sf "$PWD/.bash_profile" "$XDG_CONFIG_HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$XDG_CONFIG_HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$XDG_CONFIG_HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$XDG_CONFIG_HOME"/.tmux.conf
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

nix-env -iA nixpkgs.myPackages
